In [61]:
import pandas as pd

In [62]:
movies=pd.read_csv('NM.csv')

In [63]:
movies.head(10)

Unnamed: 0  Movie_id                        title  \
0           0       238                The Godfather   
1           1       278     The Shawshank Redemption   
2           2       240        The Godfather Part II   
3           3     19404  Dilwale Dulhania Le Jayenge   
4           4       424             Schindler's List   
5           5       129                Spirited Away   
6           6    667257            Impossible Things   
7           7       389                 12 Angry Men   
8           8    372058                   Your Name.   
9           9    496243                     Parasite   

                                              Genres release_date  \
0  [{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...   1972-03-14   
1  [{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...   1994-09-23   
2  [{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...   1974-12-20   
3  [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...   1995-10-19   
4  [{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...   1993-12-15   
5  [{'id': 16, 'name': 'Animation'}, {'id': 10751...   2001-07-20   
6  [{'id': 10751, 'name': 'Family'}, {'id': 18, '...   2021-06-17   
7                      [{'id': 18, 'name': 'Drama'}]   1957-04-10   
8  [{'id': 10749, 'name': 'Romance'}, {'id': 16, ...   2016-08-26   
9  [{'id': 35, 'name': 'Comedy'}, {'id': 53, 'nam...   2019-05-30   

                                            Keywords  \
0  [{'id': 131, 'name': 'italy'}, {'id': 697, 'na...   
1  [{'id': 378, 'name': 'prison'}, {'id': 417, 'n...   
2  [{'id': 131, 'name': 'italy'}, {'id': 700, 'na...   
3                                                 []   
4  [{'id': 818, 'name': 'based on novel or book'}...   
5  [{'id': 616, 'name': 'witch'}, {'id': 970, 'na...   
6                                                 []   
7  [{'id': 934, 'name': 'judge'}, {'id': 1417, 'n...   
8  [{'id': 4379, 'name': 'time travel'}, {'id': 4...   
9  [{'id': 5732, 'name': 'birthday party'}, {'id'...   

                                            overview  \
0  Spanning the years 1945 to 1955, a chronicle o...   
1  Framed in the 1940s for the double murder of h...   
2  In the continuing saga of the Corleone crime f...   
3  Raj is a rich, carefree, happy-go-lucky second...   
4  The true story of how businessman Oskar Schind...   
5  A young girl, Chihiro, becomes trapped in a st...   
6  Matilde is a woman who, after the death of her...   
7  The defense and the prosecution have rested an...   
8  High schoolers Mitsuha and Taki are complete s...   
9  All unemployed, Ki-taek's family takes peculia...   

                        poster_path     Budget    Revenue  popularity  \
0  /3bhkrj58Vtu7enYsRolD1fZdja1.jpg  245066411  245066411      93.552   
1  /q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg   28341469   28341469      78.664   
2  /hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg  102600000  102600000      55.752   
3  /2CAL2433ZeIihfX1Hb2139CX0pW.jpg  100000000  100000000      22.150   
4  /sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg  321365567  321365567      53.542   
5  /39wmItIWsg5sZMyRUHLkWBcuVCM.jpg  274925095  274925095      78.519   
6  /t2Ew8NZ8Ci2kqmoecZUNQUFDJnQ.jpg          0          0      10.676   
7  /ppd84D2i9W8jXmsyInGyihiSyqz.jpg    1000000    1000000      27.767   
8  /q719jXXEzOoYaps6babgKnONONX.jpg  357986087  357986087     120.614   
9  /7IiTTgloJzvGI1TAYymCfbfl3vT.jpg  257591776  257591776      61.872   

   vote_average  vote_count  
0           8.7       16814  
1           8.7       22542  
2           8.6       10187  
3           8.6        3927  
4           8.6       13382  
5           8.5       13476  
6           8.5         271  
7           8.5        6754  
8           8.5        9178  
9           8.5       14608

In [64]:
movies.describe()

Unnamed: 0       Movie_id        Budget       Revenue   popularity  \
count  9980.000000    9980.000000  9.980000e+03  9.980000e+03  9980.000000   
mean   4989.500000  166808.342886  6.158031e+07  6.158031e+07    28.376578   
std    2881.122177  218250.948419  1.516190e+08  1.516190e+08    83.770131   
min       0.000000       3.000000  0.000000e+00  0.000000e+00     0.600000   
25%    2494.750000   10153.750000  0.000000e+00  0.000000e+00    10.029000   
50%    4989.500000   31209.500000  7.600000e+06  7.600000e+06    14.059000   
75%    7484.250000  323664.250000  5.297751e+07  5.297751e+07    24.494500   
max    9979.000000  985939.000000  2.920357e+09  2.920357e+09  3890.299000   

       vote_average    vote_count  
count   9980.000000   9980.000000  
mean       6.669770   1584.761523  
std        0.717767   2708.021703  
min        5.200000      2.000000  
25%        6.100000    320.000000  
50%        6.600000    595.000000  
75%        7.200000   1503.250000  
max       10.000000  32495.000000

In [65]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9980 entries, 0 to 9979
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Unnamed: 0    9980 non-null   int64  
 1   Movie_id      9980 non-null   int64  
 2   title         9980 non-null   object 
 3   Genres        9980 non-null   object 
 4   release_date  9980 non-null   object 
 5   Keywords      9980 non-null   object 
 6   overview      9974 non-null   object 
 7   poster_path   9980 non-null   object 
 8   Budget        9980 non-null   int64  
 9   Revenue       9980 non-null   int64  
 10  popularity    9980 non-null   float64
 11  vote_average  9980 non-null   float64
 12  vote_count    9980 non-null   int64  
dtypes: float64(2), int64(5), object(6)
memory usage: 1013.7+ KB


In [66]:
movies.isnull().sum()

Unnamed: 0      0
Movie_id        0
title           0
Genres          0
release_date    0
Keywords        0
overview        6
poster_path     0
Budget          0
Revenue         0
popularity      0
vote_average    0
vote_count      0
dtype: int64

In [67]:
movies.columns

Index(['Unnamed: 0', 'Movie_id', 'title', 'Genres', 'release_date', 'Keywords',
       'overview', 'poster_path', 'Budget', 'Revenue', 'popularity',
       'vote_average', 'vote_count'],
      dtype='object')

Feature Selection Part

In [68]:
movies=movies[['Movie_id', 'title', 'Genres','Keywords',
       'overview' ]] 

In [69]:
movies.columns


Index(['Movie_id', 'title', 'Genres', 'Keywords', 'overview'], dtype='object')

In [70]:
movies['tags'] = movies['overview'] + movies['Genres']

In [73]:
movies.columns

Index(['Movie_id', 'title', 'Genres', 'Keywords', 'overview', 'tags'], dtype='object')

In [87]:
new_data = movies.drop(columns=['overview','Genres','Keywords'])

In [109]:
new_data

Movie_id                          title  \
0          238                  The Godfather   
1          278       The Shawshank Redemption   
2          240          The Godfather Part II   
3        19404    Dilwale Dulhania Le Jayenge   
4          424               Schindler's List   
...        ...                            ...   
9975    384737                 Precious Cargo   
9976    282813                    The Pyramid   
9977    134375  Home Alone: The Holiday Heist   
9978     10477                         Driven   
9979    243688                    Poltergeist   

                                                   tags  
0     Spanning the years 1945 to 1955, a chronicle o...  
1     Framed in the 1940s for the double murder of h...  
2     In the continuing saga of the Corleone crime f...  
3     Raj is a rich, carefree, happy-go-lucky second...  
4     The true story of how businessman Oskar Schind...  
...                                                 ...  
9975  After a botched heist, Eddie  a murderous crim...  
9976  An archaeological team attempt to unlock the s...  
9977  8-year-old Finn is terrified to learn his fami...  
9978  Talented rookie race-car driver Jimmy Bly has ...  
9979  A family's suburban home is invaded by angry s...  

[9980 rows x 3 columns]

In [110]:
from sklearn.feature_extraction.text import CountVectorizer

In [111]:
cv=CountVectorizer(max_features=10000,stop_words='english')

In [112]:
cv

CountVectorizer(max_features=10000, stop_words='english')

In [113]:
vector=cv.fit_transform(new_data['tags'].values.astype('U')).toarray()

In [114]:
vector[:10]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(10, 10000))

In [115]:
vector.shape

(9980, 10000)

In [116]:
feature_names = cv.get_feature_names_out()

In [117]:
feature_names

array(['000', '007', '10', ..., 'zone', 'zones', 'zoo'],
      shape=(10000,), dtype=object)

In [118]:
from sklearn.metrics.pairwise import cosine_similarity

In [127]:
similarity= cosine_similarity(vector)

In [126]:
similarity

array([[1.        , 0.24498947, 0.54772256, ..., 0.16037507, 0.04902903,
        0.22592403],
       [0.24498947, 1.        , 0.24397502, ..., 0.13715853, 0.06988566,
        0.06900656],
       [0.54772256, 0.24397502, 1.        , ..., 0.21081851, 0.03580574,
        0.21213203],
       ...,
       [0.16037507, 0.13715853, 0.21081851, ..., 1.        , 0.06290428,
        0.1987616 ],
       [0.04902903, 0.06988566, 0.03580574, ..., 0.06290428, 1.        ,
        0.02531848],
       [0.22592403, 0.06900656, 0.21213203, ..., 0.1987616 , 0.02531848,
        1.        ]], shape=(9980, 9980))

In [124]:
new_data[new_data['title']=="The Godfather"]

Movie_id          title                                               tags
0       238  The Godfather  Spanning the years 1945 to 1955, a chronicle o...

In [129]:
new_data[new_data['title']=="The Godfather"].index[0]

np.int64(0)

In [130]:
from operator import itemgetter
distance = sorted(list(enumerate(similarity[2])), key=itemgetter(1), reverse=True)

In [131]:
distance[0:5]

[(2, np.float64(1.0000000000000002)),
 (0, np.float64(0.5477225575051662)),
 (1633, np.float64(0.5152098373193084)),
 (9787, np.float64(0.4528947298916564)),
 (8250, np.float64(0.4418939581735309))]

In [102]:
for i in distance[0:5]:
    print(new_data.iloc[i[0]].title)

The Godfather Part II
The Godfather
The Godfather Part III
Gotti
Mulholland Falls


In [103]:
def recommend(movies):
    index=new_data[new_data['title']==movies].index[0]
    distance = sorted(list(enumerate(similarity[index])), key=itemgetter(1), reverse=True)
    for i in distance[0:5]:
        print(new_data.iloc[i[0]].title)

In [104]:
recommend("Iron Man")

Iron Man
Guardians of the Galaxy Vol. 2
Iron Man 3
Next Gen
Deathstroke: Knights & Dragons - The Movie


In [105]:
recommend("Guardians of the Galaxy Vol. 2")

Guardians of the Galaxy Vol. 2
Deathstroke: Knights & Dragons - The Movie
A-X-L
Next Gen
Next Avengers: Heroes of Tomorrow


In [106]:
recommend("Guardians of the Galaxy Vol. 2")

Guardians of the Galaxy Vol. 2
Deathstroke: Knights & Dragons - The Movie
A-X-L
Next Gen
Next Avengers: Heroes of Tomorrow


In [132]:
import pickle

In [133]:
pickle.dump(new_data, open('movies_list.pkl','wb'))

In [139]:
pickle.dump(similarity, open('similarity.pkl','wb'))

In [135]:
pickle.load(open('movies_list.pkl','rb'))

Movie_id                          title  \
0          238                  The Godfather   
1          278       The Shawshank Redemption   
2          240          The Godfather Part II   
3        19404    Dilwale Dulhania Le Jayenge   
4          424               Schindler's List   
...        ...                            ...   
9975    384737                 Precious Cargo   
9976    282813                    The Pyramid   
9977    134375  Home Alone: The Holiday Heist   
9978     10477                         Driven   
9979    243688                    Poltergeist   

                                                   tags  
0     Spanning the years 1945 to 1955, a chronicle o...  
1     Framed in the 1940s for the double murder of h...  
2     In the continuing saga of the Corleone crime f...  
3     Raj is a rich, carefree, happy-go-lucky second...  
4     The true story of how businessman Oskar Schind...  
...                                                 ...  
9975  After a botched heist, Eddie  a murderous crim...  
9976  An archaeological team attempt to unlock the s...  
9977  8-year-old Finn is terrified to learn his fami...  
9978  Talented rookie race-car driver Jimmy Bly has ...  
9979  A family's suburban home is invaded by angry s...  

[9980 rows x 3 columns]

In [140]:
pickle.load(open('similarity.pkl','rb'))

array([[1.        , 0.24498947, 0.54772256, ..., 0.16037507, 0.04902903,
        0.22592403],
       [0.24498947, 1.        , 0.24397502, ..., 0.13715853, 0.06988566,
        0.06900656],
       [0.54772256, 0.24397502, 1.        , ..., 0.21081851, 0.03580574,
        0.21213203],
       ...,
       [0.16037507, 0.13715853, 0.21081851, ..., 1.        , 0.06290428,
        0.1987616 ],
       [0.04902903, 0.06988566, 0.03580574, ..., 0.06290428, 1.        ,
        0.02531848],
       [0.22592403, 0.06900656, 0.21213203, ..., 0.1987616 , 0.02531848,
        1.        ]], shape=(9980, 9980))